providers: 
  - id: openai:gpt-5-mini
    config:
      temperature: 0.6
      max_tokens: 800

prompts:
  - file://prompts/prompts.txt

tests:
  # - file://tests/no-personal-advice.csv
  # - file://tests/disclaimers.csv
  # - file://tests/compliance.csv
  - file://tests/sensitive_data.csv
