
providers:
  - id: openai:gpt-5-mini
    config:
      temperature: 0.6
      max_tokens: 800

prompts:
  - file://prompts/prompts.txt


tests: 
  # - file://tests/key-financial-concepts.csv
  # - file://tests/company-specific-products.csv
  - file://tests/non-existent-products.csv